/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "primary-fixed-dim": "#22e286",
          "on-primary-fixed-variant": "#00522c",
          "surface-container-low": "#171c1f",
          "on-secondary-fixed-variant": "#39485c",
          "secondary-fixed": "#d4e3fd",
          "surface-dim": "#0f1417",
          "on-tertiary-container": "#005371",
          "outline": "#859587",
          "inverse-primary": "#006d3c",
          "on-error": "#690005",
          "on-tertiary-fixed": "#001e2c",
          "on-primary-container": "#005930",
          "on-primary": "#00391d",
          "error": "#ffb4ab",
          "on-secondary": "#223145",
          "inverse-on-surface": "#2c3134",
          "surface-bright": "#353a3d",
          "surface-variant": "#313539",
          "surface-container-high": "#262b2e",
          "surface-tint": "#22e286",
          "accent-gradient-end": "#38BDF8",
          "primary-container": "#00d97e",
          "surface-container": "#1b2023",
          "on-surface-variant": "#bacbbc",
          "background": "#0f1417",
          "on-error-container": "#ffdad6",
          "outline-variant": "#3c4a3f",
          "accent-gradient-start": "#00D97E",
          "surface-glass": "rgba(27, 42, 61, 0.6)",
          "on-tertiary-fixed-variant": "#004c69",
          "on-background": "#dfe3e7",
          "tertiary-fixed-dim": "#7bd0ff",
          "tertiary-container": "#5ec9ff",
          "secondary-container": "#3b4a5e",
          "tertiary": "#afe0ff",
          "error-container": "#93000a",
          "on-surface": "#dfe3e7",
          "secondary": "#b8c8e0",
          "surface-container-lowest": "#0a0f12",
          "primary-fixed": "#5affa2",
          "on-primary-fixed": "#00210e",
          "surface-container-highest": "#313539",
          "on-secondary-fixed": "#0c1c2f",
          "on-secondary-container": "#aab9d2",
          "primary": "#44f697",
          "tertiary-fixed": "#c4e7ff",
          "surface": "#0f1417",
          "on-tertiary": "#00354a",
          "background-deep": "#0D1B2A",
          "inverse-surface": "#dfe3e7",
          "secondary-fixed-dim": "#b8c8e0"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "gutter-mobile": "16px",
          "stack-sm": "12px",
          "gutter-desktop": "24px",
          "base": "8px",
          "stack-md": "24px",
          "stack-lg": "40px",
          "container-max": "1200px"
      },
      "fontFamily": {
          "body-lg": ["DM Sans"],
          "body-md": ["DM Sans"],
          "label-md": ["DM Sans"],
          "headline-md": ["Sora"],
          "headline-lg": ["Sora"],
          "label-sm": ["DM Sans"],
          "headline-xl": ["Sora"],
          "headline-lg-mobile": ["Sora"]
      },
      "fontSize": {
          "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
          "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
          "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
          "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
          "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
          "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
